channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1
- pip:
  - mlflow==3.7.0
  - cloudpickle==1.6.0
  - numpy==2.2.2
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
